name    'ckhall-remi'
version '0.0.2'
dependency 'stahnma/epel', 'x.x.x'
source 'http://github.com/ckhall/puppet-module-remi'
author 'ckhall'
license 'Apache License, Version 2.0'
summary 'Setup the remi package repo'
description 'Setup the remi package repo on Centos/RHEL et all'
project_page 'http://github.com/ckhall/puppet-module-remi'
